### ISSUE TITLE
[Server] Need 'image' field for 'Product' Model

### ISSUE THREAD

**Issue by jusjinuk** [wafflestudio18-5/team8-server#11]
### 구현 내용
판매자가 거래할 중고 상품에 대한 `image`를 최대 10장까지 업로드 할 수 있습니다. 이에 대한 field를 추가합니다. (image들을 저장할 `ImageModel`을 만들어서 `foreignkey`로 연결하는 방법이 좋아보입니다)
```python
# models.py
class Property(models.Model):
    address = models.TextField()
    ...

class PropertyImage(models.Model):
    property = models.ForeignKey(Property, related_name='images')
    image = models.ImageField()
```

### 참고하기 좋은 링크
- https://docs.djangoproject.com/en/3.1/topics/files/#file-storage
- https://stackoverflow.com/questions/6472233/can-i-store-images-in-mysql
- https://stackoverflow.com/questions/537593/multiple-images-per-model

**Comment by callmejustdodo** [comment]
`URLField`로 하는 것도 좋아보이네요!

**Comment by jusjinuk** [comment]
@dodo4114 [ImageField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ImageField)가 `FileField`에서의 `upload_to`를 사용할 수 있어서 [Storage.save](https://docs.djangoproject.com/en/3.1/ref/files/storage/#django.core.files.storage.Storage.save)에 전달할 때 더 직관적이지 않나요? (백엔드 담당이 아니라 조심스럽게 여쭤봅니다ㅎㅎ)

**Comment by callmejustdodo** [comment]
오 그런 기능이 있었군요 ㅋㅋㅋㅋ 이건 다른 팀원들이랑 논의해보고 결정하도록 하겠습니다. 근데 아마 우리가 EC2에 직접 저장하는 것이 아닌, 별도 저장소를 운영하고, url를 저장하는 게 권장될 것 같긴 합니다 ㅠ

**Comment by callmejustdodo** [comment]
(다른 팀 훔쳐보니 url로 저장하더라구요 그리고 ㅎㅎ)
